# Generated by Django 5.0.13 on 2025-04-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='name',
            field=models.CharField(choices=[('FLIGHTS', 'Flights'), ('STAYS', 'Stays'), ('CAR_RENTALS', 'Car Rentals'), ('ACCOUNT', 'Account')], max_length=50, unique=True),
        ),
    ]
