# Generated by Django 5.0.13 on 2025-03-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='trip_type',
            field=models.CharField(choices=[('ONE_WAY', 'One-Way'), ('ROUND_TRIP', 'Round-Trip'), ('MULTI_CITY', 'Multi-City')], default='ONE_WAY', max_length=20),
            preserve_default=False,
        ),
    ]
