# Generated by Django 5.0.13 on 2025-03-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flightbooking_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='amadeus_booking_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='trip_type',
            field=models.CharField(choices=[('ONE_WAY', 'One-Way'), ('ROUND_TRIP', 'Round-Trip'), ('MULTI_CITY', 'Multi-City')], default='ONE_WAY', max_length=20),
        ),
    ]
