# Generated by Django 5.0.13 on 2025-03-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flightbooking_amadeus_booking_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='country_calling_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='document_type',
            field=models.CharField(blank=True, choices=[('PASSPORT', 'Passport'), ('ID_CARD', 'ID Card')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='issuance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='issuance_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
