# Generated by Django 5.0.13 on 2025-03-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_passenger_birth_place_passenger_country_calling_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
