# Generated by Django 5.0.13 on 2025-03-17 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_passenger_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('airline_code', models.CharField(max_length=3)),
                ('airline_name', models.CharField(max_length=100)),
                ('departure_airport', models.CharField(max_length=3)),
                ('departure_city', models.CharField(max_length=100)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_airport', models.CharField(max_length=3)),
                ('arrival_city', models.CharField(max_length=100)),
                ('arrival_datetime', models.DateTimeField()),
                ('cabin_class', models.CharField(max_length=50)),
                ('segment_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=50, null=True)),
                ('seat_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flightdetail',
            name='booking',
        ),
        migrations.DeleteModel(
            name='FlightSearch',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='expiry_date',
            new_name='passport_expiry',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='amadeus_booking_reference',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='trip_type',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='country_calling_code',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='issuance_date',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='issuance_location',
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='booking_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='booking_type',
            field=models.CharField(choices=[('ONE_WAY', 'One Way'), ('ROUND_TRIP', 'Round Trip'), ('MULTI_CITY', 'Multi City')], default='One Way', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr'), ('MS', 'Ms'), ('MRS', 'Mrs'), ('MISS', 'Miss'), ('DR', 'Dr')], default='Mr', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='booking_reference',
            field=models.CharField(default='AEF95183B5', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.flightbooking'),
        ),
        migrations.AddField(
            model_name='passengerbooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_bookings', to='flights.flightbooking'),
        ),
        migrations.AddField(
            model_name='passengerbooking',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.passenger'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='flights.flightbooking'),
        ),
        migrations.DeleteModel(
            name='FlightDetail',
        ),
    ]
