# Generated by Django 5.0.13 on 2025-03-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_servicefeesetting_flightbooking_base_flight_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='booking_reference',
            field=models.CharField(default='E9E9D4A4E8', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
    ]
