# Generated by Django 5.0.13 on 2025-03-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_alter_flightbooking_booking_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='booking_reference',
            field=models.CharField(default='1403E5AE0E', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10
            ),
        ),
    ]
