# Generated by Django 5.0.13 on 2025-03-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_alter_flightbooking_booking_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='address_line1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='address_line2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='booking_reference',
            field=models.CharField(default='9EA5E23D84', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
    ]
