# Generated by Django 5.0.13 on 2025-03-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_passenger_address_line1_passenger_address_line2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='booking_reference',
            field=models.CharField(default='1B2FFA2CD8', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
    ]
