# Generated by Django 5.0.13 on 2025-03-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_alter_flightbooking_booking_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='booking_reference',
            field=models.CharField(default='2A48DFE0D0', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
