# Generated by Django 5.0.13 on 2025-03-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0015_alter_flightbooking_booking_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='booking_reference',
            field=models.CharField(default='3E492E0734', max_length=10, unique=True),
        ),
    ]
