# Generated by Django 5.0.13 on 2025-03-30 16:19

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0017_alter_flight_options_alter_flightbooking_options_and_more'),
        ('stay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='booking',
            field=auto_prefetch.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_payment', to='stay.booking'),
        ),
    ]
