# Generated by Django 5.0.13 on 2025-04-01 12:26

import core.applications.flights.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0020_alter_flight_options_flight_aircraft_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='booking_reference',
            field=models.CharField(default=core.applications.flights.models.FlightBooking.generate_booking_reference, max_length=100, unique=True),
        ),
    ]
