# Generated by Django 5.0.13 on 2025-03-26 11:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('STANDARD', 'Standard Car Rental'), ('PREMIUM', 'Premium Cars'), ('LUXURY', 'Luxury Vehicles'), ('TRANSFER', 'Transfer Service')], default='STANDARD', max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percentage fee (e.g., 10.50 for 10.5%)', max_digits=5)),
                ('minimum_fee', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Minimum fee amount in currency', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Car Service Fee',
                'verbose_name_plural': 'Car Service Fees',
                'ordering': ['fee_type'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('AMADEUS_FAILED', 'Amadeus Booking Failed'), ('REFUND_PENDING', 'Refund Pending'), ('REFUNDED', 'Refunded')], max_length=20)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='amadeus_booking_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='base_transfer_cost',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default='5', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='additional_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('AMADEUS_FAILED', 'Amadeus Booking Failed'), ('REFUND_PENDING', 'Refund Pending'), ('REFUNDED', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('REFUND_PENDING', 'Refund Pending')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='carservicefee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('fee_type',), name='unique_active_fee_per_type'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cars.booking'),
        ),
    ]
