# Generated by Django 5.0.13 on 2025-03-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_booking_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transfer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
