# Generated by Django 5.0.13 on 2025-03-30 16:19

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_booking_passengers'),
        ('stay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='booking',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='stay.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=auto_prefetch.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_payment', to='stay.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('REFUND_PENDING', 'Refund Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], max_length=20),
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('dropoff_date', models.DateField()),
                ('dropoff_time', models.TimeField()),
                ('child_seats', models.IntegerField(default=0)),
                ('passengers', models.IntegerField(default=1)),
                ('named_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_reference', models.CharField(max_length=50, unique=True)),
                ('amadeus_booking_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('base_transfer_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('transfer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('booking', auto_prefetch.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_booking', to='stay.booking')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car')),
                ('dropoff_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_bookings', to='cars.location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_bookings', to='cars.location')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
