# Generated by Django 5.0.13 on 2025-04-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_carbooking_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='customer_email',
            field=models.EmailField(default='no-email@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carbooking',
            name='customer_first_name',
            field=models.CharField(default='no_name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carbooking',
            name='customer_last_name',
            field=models.CharField(default='no_last_name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carbooking',
            name='customer_phone',
            field=models.CharField(default='123456789', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carbooking',
            name='customer_title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
