# Generated by Django 5.0.13 on 2025-04-19 20:20

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_carbooking_customer_email_and_more'),
        ('stay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=auto_prefetch.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stay.booking'),
        ),
    ]
