# Generated by Django 5.0.13 on 2025-05-11 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_payment_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passengers', models.IntegerField(default=1)),
                ('dropoff_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_dropoffs', to='cars.location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_pickups', to='cars.location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pickup_location', 'dropoff_location'], name='cars_carsea_pickup__a62077_idx'), models.Index(fields=['created_at'], name='cars_carsea_created_352808_idx')],
            },
        ),
    ]
