# Generated by Django 5.0.13 on 2025-04-08 10:38

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Found another app', 'Found another app'), ('Too many notifications', 'Too many notifications'), ('Overloaded with content', 'Overloaded with content'), ('Security concern', 'Security concern'), ('Others', 'Others')], default='Others', max_length=50)),
                ('additional_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
