# Generated by Django 5.0.13 on 2025-05-17 06:22

import core.applications.chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_assigned_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.applications.chat.models.chat_attachment_path),
        ),
        migrations.DeleteModel(
            name='ChatAttachment',
        ),
    ]
